os: linux
dist: bionic
language: scala
scala:
  - 2.12.12
  - 2.13.3
jdk:
  - openjdk8
env:
  - SCALAJS_VERSION=1.1.1
  - SCALAJS_VERSION=0.6.33
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.sbt/boot
script:
  - sbt clean ++$TRAVIS_SCALA_VERSION test
